#!/usr/bin/env bash

source /opt/resource/lib/log

set_log_prefix "test/run"
log "start"

export SRC_DIR=$PWD
export BUILD_ID=1
export BUILD_NAME='my-build'
export BUILD_JOB_NAME='my-build-job'
export BUILD_PIPELINE_NAME='my-build-pipeline'
export ATC_EXTERNAL_URL='127.0.0.1/atc'

COMMAND="/opt/resource/${1:-check}"
log "command" $COMMAND

exec $COMMAND ${@:2}

log "end"
