#!/usr/bin/env bash

source /opt/resource/lib/colours

LOG_PREFIX=''

# /**
#  * Set the prefix for log messages
#  */
set_log_prefix () {
  ([ -n "${1}" ]) \
    && LOG_PREFIX="${1}." \
    || LOG_PREFIX=""
}

# /**
#  * logs message to stdout with optional prefix
#  * Print to stdout
#  * @void
#  */
log () {
  clr_bold clr_green "${LOG_PREFIX}${1} " -n; \
  	[ ${#@} -gt 1 ] && clr_reset ${@:2} 1>&2
}

# /**
#  * aborts program with message
#  * @return {Exit 1}
#  */
abort () {
  clr_bold clr_red "${LOG_PREFIX}abort " -n; echo $@ 1>&2
  exit 1
}

# /**
#  * Return success
#  * @return {Exit 0}
#  */
success () {
  echo $@
  exit 0
}