#!/usr/bin/env bash

smb () {
	([ -n "${1}" ]) \
		&& connection=$1 \
		|| abort "missing connect"

	echo "/usr/bin/smbclient $connection --grepable --debuglevel=0 ${@:2}"
}

smb_get () {
	log "smb_get" $@

	# uri string
	([ -n "${1}" ]) \
		&& uri=$1 \
		|| abort "missing //server/share"

	# path to bundle and download
	([ -n "${2}" ]) \
		&& path="${2}" \
		|| path=""

	# archive to download into
	([ -n "${3}" ]) \
		&& archive=$3 \
		|| archive=""

	# username and password
	([ -n "${4}" ]) \
		&& user="--user=${4} " \
		|| user=""
	([ -n "${5}" ]) \
		&& password="${5} " \
		|| password="'' -N "

	smb "$uri $password $user" -Tc $archive $path
}

smb_put () {
	log "smb_put" $@

	# uri string
	([ -n "${1}" ]) \
		&& uri=$1 \
		|| abort "missing //server/share"

	# path to upload into
	([ -n "${2}" ]) \
		&& path="--directory=${2}" \

	# archive to upload and unpack
	([ -n "${3}" ]) \
		&& archive=$3 \
		|| abort "missing archive to upload"

	# username and password
	([ -n "${4}" ]) \
		&& user="--user=${4} " \
		|| user=""
	([ -n "${5}" ]) \
		&& password="${5} " \
		|| password="'' -N "

	smb "$uri $password $user $path" -Tx $archive
}


