#!/usr/bin/env bash

smb () {
	([ -n "${1}" ]) \
		&& connection=$1 \
		|| abort "missing connect"

	/usr/bin/smbclient $connection ${@:1}
}

smb_get () {
	([ -n "${1}" ]) \
		&& server=$1 \
		|| abort "missing server"
	([ -n "${2}" ]) \
		&& share=$2 \
		|| abort "missing share"
	([ -n "${3}" ]) \
		&& archive=$3 \
		|| archive=""
	([ -n "${4}" ]) \
		&& manifest=$4 \
		|| manifest=""
	([ -n "${5}" ]) \
		&& user="--user=$5 " \
		|| user=""
	([ -n "${6}" ]) \
		&& password="$6 " \
		|| password="'' -N "

	log "manifest" $manifest

	smb "//${server}/${share} $password $user" -TcF $archive $manifest

}

smb_put () {
	([ -n "${1}" ]) \
		&& server=$1 \
		|| abort "missing server"
	([ -n "${2}" ]) \
		&& share=$2 \
		|| abort "missing share"
	([ -n "${3}" ]) \
		&& manifest=$3 \
		|| manifest=""
	([ -n "${4}" ]) \
		&& user="--user=$4 " \
		|| user=""
	([ -n "${5}" ]) \
		&& password="$5 " \
		|| password="'' -N "

	smb "//${server}/${share} $password $user" --grepable --debuglevel=0 -TXx $manifest

}

smb_create_manifest () {
	([ -n "${1}" ]) \
		&& map=$1 \
		|| abort "missing map"
	([ -n "${2}" ]) \
		&& target=$2 \
		|| abort "missing target file"

	printf "%s\n" "${map}" > $target
}

smb_generate_hash () {
	PLATFORM=`uname`
	MD5_TOOL="md5sum"
	if [ $PLATFORM = "Darwin" ]; then
	  MD5_TOOL="md5"
	fi
	$MD5_TOOL < $@ | awk '{ print $1 }'
}