#!/bin/node

const smb = require('smb2'),
	RequestPayload = require('./lib/request').RequestPayload;

RequestPayload()
	.then((payload) => {
			const {
				share,
				server,
				domain,
				user,
				path,
				password
			} = payload.source;

			const options = {
					share: "\\\\" + server + "\\" + share,
					domain: domain || 'WORKGROUP',
					username: user,
					password: password
				};

			const client = new smb(options);

			client
				.readdir(path, function (err, files) {
					if (!err) {

						files.unshift('[')
						files.push(']')
						files.map(bit => process.stdout.write(bit))
						process.stdout.write('\n')
					}
				});

	})
	.then(stdout);
