#!/usr/bin/env bash

source ./lib/log
source ./lib/smb

set_log_prefix "resource/check"

SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

LOCAL_PATH=/mnt/storage

VERSION=$(jq -r '.version.ref // ""' < $SCRIPT_INPUT)

SMB_SERVER=$(jq -r '.source.server // ""' < $SCRIPT_INPUT)
SMB_SHARE=$(jq -r '.source.share // ""' < $SCRIPT_INPUT)
SMB_PATHS=$(jq -r '.source.paths // ""' < $SCRIPT_INPUT)
SMB_USER=$(jq -r '.source.user // ""' < $SCRIPT_INPUT)
SMB_PASSWORD=$(jq -r '.source.password // ""' < $SCRIPT_INPUT)

log "status" "  localPath:" $LOCAL_PATH
log "status" "    version:" $VERSION
log "status" "       user:" $SMB_USER
log "status" "   password:" $SMB_PASSWORD
log "status" "     server:" $SMB_SERVER
log "status" "      share:" $SMB_SHARE
log "status" "       path:" $SMB_PATH
log "status" "    pattern:" $SMB_PATTERN

smb_get $SMB_SERVER $SMB_SHARE $SMB_PATH $SMB_PATTERN $SMB_USER $SMB_PASSWORD $LOCAL_PATH

# echo $DIR 1>&2
# echo ${#REFS} 1>&2

# NEW_REF="{ \"ref\": \"$DIR\" }"
# if [ "${#REFS}" != "0" ]; then
#   NEW_REF="{ \"ref\": \"$DIR\" },"
# fi

# REFS=$NEW_REF$REFS # See the concat

# if [ "$DIR" = "$VERSION" ]; then
#   break
# fi

